/* eslint-disable no-undef */
setStocks &&
  setStocks([
    {
      code: '600906',
      price: 10.75,
      name: '财达证券',
      exchange: 'SH',
    },
    {
      code: '300753',
      price: 27.36,
      name: '爱朋医疗',
      exchange: 'SZ',
    },
    {
      code: '603828',
      price: 5.29,
      name: '柯利达',
      exchange: 'SH',
    },
    {
      code: '300375',
      price: 6.15,
      name: '鹏翎股份',
      exchange: 'SZ',
    },
    {
      code: '002902',
      price: 38.36,
      name: '铭普光磁',
      exchange: 'SZ',
    },
    {
      code: '603682',
      price: 9.14,
      name: '锦和商管',
      exchange: 'SH',
    },
    {
      code: '603026',
      price: 348.28,
      name: '胜华新材',
      exchange: 'SH',
    },
    {
      code: '002722',
      price: 19.29,
      name: '物产金轮',
      exchange: 'SZ',
    },
    {
      code: '601595',
      price: 42.31,
      name: '上海电影',
      exchange: 'SH',
    },
    {
      code: '002174',
      price: 26.53,
      name: '游族网络',
      exchange: 'SZ',
    },
    {
      code: '002377',
      price: 4.49,
      name: '国创高新',
      exchange: 'SZ',
    },
    {
      code: '601326',
      price: 4.86,
      name: '秦港股份',
      exchange: 'SH',
    },
    {
      code: '300377',
      price: 10,
      name: '赢时胜',
      exchange: 'SZ',
    },
    {
      code: '300901',
      price: 17.14,
      name: '中胤时尚',
      exchange: 'SZ',
    },
    {
      code: '600302',
      price: 8.61,
      name: '标准股份',
      exchange: 'SH',
    },
    {
      code: '300790',
      price: 36.07,
      name: '宇瞳光学',
      exchange: 'SZ',
    },
    {
      code: '605588',
      price: 61.19,
      name: '冠石科技',
      exchange: 'SH',
    },
    {
      code: '603933',
      price: 25.71,
      name: '睿能科技',
      exchange: 'SH',
    },
    {
      code: '002898',
      price: 15.35,
      name: '赛隆药业',
      exchange: 'SZ',
    },
    {
      code: '603716',
      price: 15.98,
      name: '塞力医疗',
      exchange: 'SH',
    },
    {
      code: '600248',
      price: 7.63,
      name: '陕建股份',
      exchange: 'SH',
    },
    {
      code: '300844',
      price: 62.22,
      name: '山水比德',
      exchange: 'SZ',
    },
    {
      code: '600239',
      price: 3.88,
      name: '云南城投',
      exchange: 'SH',
    },
    {
      code: '600928',
      price: 4.82,
      name: '西安银行',
      exchange: 'SH',
    },
    {
      code: '002893',
      price: 18.18,
      name: '京能热力',
      exchange: 'SZ',
    },
    {
      code: '301075',
      price: 35.54,
      name: '多瑞医药',
      exchange: 'SZ',
    },
    {
      code: '601086',
      price: 8.44,
      name: '国芳集团',
      exchange: 'SH',
    },
    {
      code: '603087',
      price: 46.55,
      name: '甘李药业',
      exchange: 'SH',
    },
    {
      code: '000564',
      price: 2.47,
      name: 'st大集',
      exchange: 'SZ',
    },
    {
      code: '002896',
      price: 48.2,
      name: '中大立德',
      exchange: 'SZ',
    },
    {
      code: '300437',
      price: 51.13,
      name: '清水源',
      exchange: 'SZ',
    },
    {
      code: '000752',
      price: 12.94,
      name: 'st西发',
      exchange: 'SZ',
    },
    {
      code: '000890',
      price: 6.15,
      name: '法尔胜',
      exchange: 'SZ',
    },
    {
      code: '603042',
      price: 25.4,
      name: '华脉科技',
      exchange: 'SH',
    },
    {
      code: '000936',
      price: 15.04,
      name: '华西股份',
      exchange: 'SZ',
    },
    {
      code: '603087',
      price: 203.36,
      name: '甘李药业',
      exchange: 'SH',
    },
    {
      code: '002193',
      price: 14.65,
      name: '如意集团',
      exchange: 'SZ',
    },
    {
      code: '603536',
      price: 20.22,
      name: '惠发食品',
      exchange: 'SH',
    },
    {
      code: '270100',
      price: 1556.03,
      name: '半导体',
      exchange: 'SH',
    },
    {
      code: 'BK1128',
      price: 2278.21,
      name: 'cpo概念',
      exchange: 'SH',
    },
    {
      code: '603083',
      price: 78.6,
      name: '剑桥科技',
      exchange: 'SH',
    },
    {
      code: '603501',
      price: 255.09,
      name: '韦尔股份',
      exchange: 'SH',
    },
    {
      code: '300114',
      price: 64.85,
      name: '中航电测',
      exchange: 'SZ',
    },
    {
      code: '000980',
      price: 8.5,
      name: '众泰汽车',
      exchange: 'SZ',
    },
    {
      code: '430300',
      price: 1145.28,
      name: '房地产服务',
      exchange: 'SH',
    },
    {
      code: '000514',
      price: 5.77,
      name: '渝开发',
      exchange: 'SZ',
    },
    {
      code: '280200',
      price: 31342.8,
      name: '汽车零部件',
      exchange: 'SH',
    },
    {
      code: 'BK1046',
      price: 1648.15,
      name: '游戏',
      exchange: 'SH',
    },
    {
      code: '003597',
      price: 1540.1,
      name: '水利建设',
      exchange: 'SZ',
    },
    {
      code: '003640',
      price: 1336.2,
      name: '机器人概念',
      exchange: 'SZ',
    },
    {
      code: '002896',
      price: 48.2,
      name: '中大力德',
      exchange: 'SZ',
    },
    {
      code: '300549',
      price: 34,
      name: '德优精密',
      exchange: 'SZ',
    },
    {
      code: '002553',
      price: 21.57,
      name: '南方精工',
      exchange: 'SZ',
    },
    {
      code: '600280',
      price: 6.1,
      name: '中央商场',
      exchange: 'SH',
    },
    {
      code: '301281',
      price: 63.99,
      name: '科源制药',
      exchange: 'SZ',
    },
    {
      code: '300238',
      price: 23.38,
      name: '冠昊生物',
      exchange: 'SZ',
    },
    {
      code: '603106',
      price: 10.25,
      name: '恒银科技',
      exchange: 'SH',
    },
    {
      code: '600468',
      price: 7.66,
      name: '百利电气',
      exchange: 'SH',
    },
    {
      code: '002281',
      price: 44.23,
      name: '光迅科技',
      exchange: 'SZ',
    },
    {
      code: '600613',
      price: 9.31,
      name: '神奇制药',
      exchange: 'SH',
    },
    {
      code: '000802',
      price: 9.9,
      name: '北京文化',
      exchange: 'SZ',
    },
    {
      code: '300499',
      price: 25.72,
      name: '高澜股份',
      exchange: 'SZ',
    },
    {
      code: '600283',
      price: 19.3,
      name: '钱江水利',
      exchange: 'SH',
    },
    {
      code: '000037',
      price: 14.78,
      name: '深南电A',
      exchange: 'SZ',
    },
    {
      code: '600822',
      price: 17.86,
      name: '上海物贸',
      exchange: 'SH',
    },
    {
      code: '603322',
      price: 48.01,
      name: '超讯通信',
      exchange: 'SH',
    },
    {
      code: '601360',
      price: 20.85,
      name: '三六零',
      exchange: 'SH',
    },
    {
      code: '603779',
      price: 14.46,
      name: '威龙股份',
      exchange: 'SH',
    },
    {
      code: '061297',
      price: 1721.54,
      name: '边缘计算',
      exchange: 'SH',
    },
    {
      code: '601858',
      price: 50.79,
      name: '中国科传',
      exchange: 'SH',
    },
    {
      code: '600272',
      price: 18.3,
      name: '开开实业',
      exchange: 'SH',
    },
    {
      code: '301234',
      price: 54.8,
      name: '五洲医疗',
      exchange: 'SZ',
    },
    {
      code: '300565',
      price: 58.39,
      name: '科信技术',
      exchange: 'SZ',
    },
    {
      code: '300426',
      price: 19.45,
      name: '康德影视',
      exchange: 'SZ',
    },
    {
      code: '300570',
      price: 64.39,
      name: '太辰光',
      exchange: 'SZ',
    },
    {
      code: '000899',
      price: 17,
      name: '赣能股份',
      exchange: 'SZ',
    },
    {
      code: '600706',
      price: 22.1,
      name: '曲江文旅',
      exchange: 'SH',
    },
    {
      code: '003800',
      price: 1374.96,
      name: '人工智能',
      exchange: 'SZ',
    },
    {
      code: '002590',
      price: 15.74,
      name: '万安科技',
      exchange: 'SZ',
    },
    {
      code: '601990',
      price: 9.5,
      name: '南京证券',
      exchange: 'SH',
    },
    {
      code: '300377',
      price: 10.6,
      name: '赢时胜',
      exchange: 'SZ',
    },
    {
      code: '603569',
      price: 17.92,
      name: '长久物流',
      exchange: 'SH',
    },
    {
      code: '002173',
      price: 13.52,
      name: '创新医疗',
      exchange: 'SZ',
    },
    {
      code: '605580',
      price: 17.73,
      name: '恒盛能源',
      exchange: 'SH',
    },
    {
      code: '430300',
      price: 1145.28,
      name: '房地产服务',
      exchange: 'SH',
    },
    {
      code: 'BK1040',
      price: 1728.18,
      name: '中药',
      exchange: 'SH',
    },
    {
      code: '688063',
      price: 509.51,
      name: '派能科技',
      exchange: 'SH',
    },
    {
      code: '601127',
      price: 90.5,
      name: '赛力斯',
      exchange: 'SH',
    },
    {
      code: '600138',
      price: 16.88,
      name: '中青旅',
      exchange: 'SH',
    },
    {
      code: '002181',
      price: 8.16,
      name: '粤传媒',
      exchange: 'SZ',
    },
    {
      code: '000980',
      price: 5.3,
      name: '众泰汽车',
      exchange: 'SZ',
    },
    {
      code: '603357',
      price: 13.61,
      name: '设计总院',
      exchange: 'SH',
    },
    {
      code: '601698',
      price: 25.66,
      name: '中国卫通',
      exchange: 'SH',
    },
    {
      code: '603131',
      price: 16.47,
      name: '上海沪工',
      exchange: 'SH',
    },
    {
      code: '002186',
      price: 22.92,
      name: '全聚德',
      exchange: 'SZ',
    },
    {
      code: '300475',
      price: 50.1,
      name: '香农芯创',
      exchange: 'SZ',
    },
    {
      code: 'BK0448',
      price: 12561.73,
      name: '通讯设备',
      exchange: 'SH',
    },
    {
      code: '300364',
      price: 27.76,
      name: '中文在线',
      exchange: 'SZ',
    },
    {
      code: '603918',
      price: 38.64,
      name: '金桥信息',
      exchange: 'SH',
    },
    {
      code: '000656',
      price: 2.75,
      name: '金科股份',
      exchange: 'SZ',
    },
    {
      code: '600239',
      price: 3.88,
      name: '云南城投',
      exchange: 'SH',
    },
    {
      code: '688318',
      price: 184.9,
      name: '财富趋势',
      exchange: 'SH',
    },
    {
      code: '600248',
      price: 7.63,
      name: '陕西建工',
      exchange: 'SH',
    },
    {
      code: '001324',
      price: 41.87,
      name: '长青科技',
      exchange: 'SZ',
    },
    {
      code: '000826',
      price: 5.33,
      name: '启迪环境',
      exchange: 'SZ',
    },
    {
      code: '301289',
      price: 75.97,
      name: '国缆检测',
      exchange: 'SZ',
    },
    {
      code: '301159',
      price: 76.77,
      name: '三维天地',
      exchange: 'SZ',
    },
    {
      code: '603137',
      price: 27.47,
      name: '恒尚节能',
      exchange: 'SH',
    },
    {
      code: '600743',
      price: 2.6,
      name: '华远地产',
      exchange: 'SH',
    },
    {
      code: '002858',
      price: 30.31,
      name: '力生体育',
      exchange: 'SZ',
    },
    {
      code: '301125',
      price: 26.21,
      name: '腾亚精工',
      exchange: 'SZ',
    },
    {
      code: '300094',
      price: 8.3,
      name: '国联水产',
      exchange: 'SZ',
    },
    {
      code: 'BK0711',
      price: 1094.34,
      name: '券商概念',
      exchange: 'SH',
    },
    {
      code: '002157',
      price: 25.98,
      name: '正邦科技',
      exchange: 'SZ',
    },
    {
      code: '002336',
      price: 20.64,
      name: '人人乐',
      exchange: 'SZ',
    },
    {
      code: '002761',
      price: 47.09,
      name: '浙江建投',
      exchange: 'SZ',
    },
    {
      code: '000756',
      price: 48.65,
      name: '新华制药',
      exchange: 'SZ',
    },
    {
      code: '603196',
      price: 28.7,
      name: '日播时尚',
      exchange: 'SH',
    },
    {
      code: '301169',
      price: 79.15,
      name: '零点有数',
      exchange: 'SZ',
    },
    {
      code: '301083',
      price: 30.32,
      name: '百胜智能',
      exchange: 'SZ',
    },
    {
      code: '002362',
      price: 40.24,
      name: '汉王科技',
      exchange: 'SZ',
    },
    {
      code: '002866',
      price: 54.4,
      name: '传艺科技',
      exchange: 'SZ',
    },
    {
      code: '605069',
      price: 15.7,
      name: '正和生态',
      exchange: 'SH',
    },
    {
      code: '605398',
      price: 39.45,
      name: '新炬网络',
      exchange: 'SH',
    },
    {
      code: '000025',
      price: 35.27,
      name: '特力A',
      exchange: 'SZ',
    },
    {
      code: '603897',
      price: 65.13,
      name: '长城科技',
      exchange: 'SH',
    },
    {
      code: '002875',
      price: 29.62,
      name: '安奈儿',
      exchange: 'SZ',
    },
    {
      code: '300261',
      price: 31.34,
      name: '雅本化学',
      exchange: 'SZ',
    },
    {
      code: '603137',
      price: 27.47,
      name: '恒尚节能',
      exchange: 'SH',
    },
    {
      code: '002553',
      price: 21.57,
      name: '南方精工',
      exchange: 'SZ',
    },
    {
      code: '002366',
      price: 8.67,
      name: '融发核电',
      exchange: 'SZ',
    },
    {
      code: '003027',
      price: 33.99,
      name: '同兴环保',
      exchange: 'SZ',
    },
    {
      code: '301368',
      price: 72.37,
      name: '丰立智能',
      exchange: 'SZ',
    },
    {
      code: '601099',
      price: 5.28,
      name: '太平洋',
      exchange: 'SH',
    },
    {
      code: '300549',
      price: 34,
      name: '优德精密',
      exchange: 'SZ',
    },
    {
      code: '301338',
      price: 62.82,
      name: '凯格精机',
      exchange: 'SZ',
    },
    {
      code: '002995',
      price: 45.6,
      name: '天地在线',
      exchange: 'SZ',
    },
    {
      code: '301218',
      price: 62.95,
      name: '华是科技',
      exchange: 'SZ',
    },
    {
      code: '601065',
      price: 18.6,
      name: '江盐集团',
      exchange: 'SH',
    },
    {
      code: '002209',
      price: 15.48,
      name: '达意隆',
      exchange: 'SZ',
    },
    {
      code: '000882',
      price: 2.27,
      name: '华联股份',
      exchange: 'SZ',
    },
    {
      code: '605188',
      price: 13.15,
      name: '国光连锁',
      exchange: 'SH',
    },
    {
      code: '301228',
      price: 30.48,
      name: '实扑检测',
      exchange: 'SZ',
    },
    {
      code: '002497',
      price: 44.56,
      name: '雅化集团',
      exchange: 'SZ',
    },
    {
      code: '001300',
      price: 23.49,
      name: '三柏硕',
      exchange: 'SZ',
    },
    {
      code: '600072',
      price: 30.7,
      name: '中船科技',
      exchange: 'SH',
    },
    {
      code: '000917',
      price: 9.16,
      name: '电广传媒',
      exchange: 'SZ',
    },
    {
      code: '300502',
      price: 81.18,
      name: '新易盛',
      exchange: 'SZ',
    },
    {
      code: '600257',
      price: 10.64,
      name: '大湖股份',
      exchange: 'SH',
    },
    {
      code: '300948',
      price: 22.8,
      name: '冠中生态',
      exchange: 'SZ',
    },
    {
      code: '300854',
      price: 23.09,
      name: '中兰环保',
      exchange: 'SZ',
    },
    {
      code: '301095',
      price: 161.6,
      name: '广立微',
      exchange: 'SZ',
    },
    {
      code: '300380',
      price: 42,
      name: '安硕信息',
      exchange: 'SZ',
    },
    {
      code: '601688',
      price: 18.54,
      name: '华泰证券',
      exchange: 'SH',
    },
    {
      code: '000712',
      price: 17.96,
      name: '锦龙股份',
      exchange: 'SZ',
    },
    {
      code: '603025',
      price: 17.11,
      name: '大豪科技',
      exchange: 'SH',
    },
    {
      code: '002060',
      price: 10.16,
      name: '粤水电',
      exchange: 'SZ',
    },
    {
      code: '603799',
      price: 115.72,
      name: '华友钴业',
      exchange: 'SH',
    },
    {
      code: '300207',
      price: 54.85,
      name: '欣旺达',
      exchange: 'SZ',
    },
    {
      code: '601127',
      price: 51.28,
      name: '赛力斯',
      exchange: 'SH',
    },
    {
      code: '600310',
      price: 6.48,
      name: '桂东电力',
      exchange: 'SH',
    },
    {
      code: '601811',
      price: 21.94,
      name: '新华文轩',
      exchange: 'SH',
    },
    {
      code: '300678',
      price: 63.32,
      name: '中科信息',
      exchange: 'SZ',
    },
    {
      code: '300885',
      price: 12.9,
      name: '海昌新材',
      exchange: 'SZ',
    },
    {
      code: '603127',
      price: 92.4,
      name: '邵衍新药',
      exchange: 'SH',
    },
    {
      code: '600864',
      price: 7.41,
      name: '哈投股份',
      exchange: 'SH',
    },
    {
      code: '000988',
      price: 46.39,
      name: '华工科技',
      exchange: 'SZ',
    },
    {
      code: '603326',
      price: 17.46,
      name: '我乐家居',
      exchange: 'SH',
    },
    {
      code: '603799',
      price: 115.72,
      name: '华友钴业',
      exchange: 'SH',
    },
    {
      code: '600629',
      price: 11.96,
      name: '华建集团',
      exchange: 'SH',
    },
    {
      code: '300844',
      price: 66.22,
      name: '山水比德',
      exchange: 'SZ',
    },
    {
      code: '300031',
      price: 32.77,
      name: '宝通科技',
      exchange: 'SZ',
    },
    {
      code: '300280',
      price: 63.65,
      name: '紫天科技',
      exchange: 'SZ',
    },
    {
      code: '600792',
      price: 6.36,
      name: '云煤能源',
      exchange: 'SH',
    },
    {
      code: '300749',
      price: 12.35,
      name: '顶固集创',
      exchange: 'SZ',
    },
    {
      code: '300184',
      price: 6.76,
      name: '力源信息',
      exchange: 'SZ',
    },
    {
      code: '002204',
      price: 10.07,
      name: '大连重工',
      exchange: 'SZ',
    },
    {
      code: '002317',
      price: 41.1,
      name: '众生药业',
      exchange: 'SZ',
    },
    {
      code: '300989',
      price: 31.55,
      name: '蕾奥规划',
      exchange: 'SZ',
    },
    {
      code: '605011',
      price: 45.16,
      name: '杭州热电',
      exchange: 'SH',
    },
    {
      code: '300058',
      price: 14.9,
      name: '蓝色光标',
      exchange: 'SZ',
    },
    {
      code: '002310',
      price: 3.35,
      name: '东方园林',
      exchange: 'SZ',
    },
    {
      code: '002336',
      price: 18.88,
      name: '人人乐',
      exchange: 'SZ',
    },
    {
      code: '300654',
      price: 21.83,
      name: '世纪天鸿',
      exchange: 'SZ',
    },
    {
      code: '002630',
      price: 3.34,
      name: '华西能源',
      exchange: 'SZ',
    },
    {
      code: '300337',
      price: 17,
      name: '银邦股份',
      exchange: 'SZ',
    },
    {
      code: '300467',
      price: 21.63,
      name: '迅游科技',
      exchange: 'SZ',
    },
    {
      code: '300533',
      price: 63.2,
      name: '冰川网络',
      exchange: 'SZ',
    },
    {
      code: '600095',
      price: 10.3,
      name: '湘财股份',
      exchange: 'SH',
    },
    {
      code: '300459',
      price: 9.47,
      name: '汤姆猫',
      exchange: 'SZ',
    },
    {
      code: '605588',
      price: 68.12,
      name: '冠石科技',
      exchange: 'SH',
    },
    {
      code: '603258',
      price: 56.84,
      name: '电魂网络',
      exchange: 'SH',
    },
    {
      code: '000851',
      price: 7.31,
      name: '高鸿股份',
      exchange: 'SZ',
    },
    {
      code: '603527',
      price: 23.71,
      name: '众源新材',
      exchange: 'SH',
    },
    {
      code: '600072',
      price: 30.7,
      name: '中船科技',
      exchange: 'SH',
    },
    {
      code: '301036',
      price: 27.29,
      name: '双乐股份',
      exchange: 'SZ',
    },
    {
      code: '300418',
      price: 70.66,
      name: '昆仑万维',
      exchange: 'SZ',
    },
    {
      code: '300172',
      price: 7.32,
      name: '中电环保',
      exchange: 'SZ',
    },
    {
      code: '603612',
      price: 49.69,
      name: '索通发展',
      exchange: 'SH',
    },
    {
      code: '300172',
      price: 9.32,
      name: '中电环保',
      exchange: 'SZ',
    },
    {
      code: '002642',
      price: 9.29,
      name: '荣联科技',
      exchange: 'SZ',
    },
    {
      code: '603069',
      price: 45.78,
      name: '海汽集团',
      exchange: 'SH',
    },
    {
      code: '000766',
      price: 14.7,
      name: '通马金化',
      exchange: 'SZ',
    },
    {
      code: '002889',
      price: 39.65,
      name: '东方嘉盛',
      exchange: 'SZ',
    },
    {
      code: '601188',
      price: 5.42,
      name: '龙江交通',
      exchange: 'SH',
    },
    {
      code: '301203',
      price: 71.21,
      name: '国泰环保',
      exchange: 'SZ',
    },
    {
      code: '600615',
      price: 12.24,
      name: '丰华股份',
      exchange: 'SH',
    },
    {
      code: '000046',
      price: 3.39,
      name: 'st泛海',
      exchange: 'SZ',
    },
    {
      code: '603042',
      price: 21.91,
      name: '华脉科技',
      exchange: 'SH',
    },
    {
      code: '300780',
      price: 36.96,
      name: '德恩精工',
      exchange: 'SZ',
    },
    {
      code: '600355',
      price: 7.57,
      name: '精伦电子',
      exchange: 'SH',
    },
    {
      code: '002855',
      price: 52.36,
      name: '捷荣技术',
      exchange: 'SZ',
    },
    {
      code: '300763',
      price: 291.72,
      name: '锦浪科技',
      exchange: 'SZ',
    },
    {
      code: '002204',
      price: 10.07,
      name: '大连重工',
      exchange: 'SZ',
    },
    {
      code: '603799',
      price: 115.72,
      name: '华友钴业',
      exchange: 'SH',
    },
    {
      code: '395004',
      price: 3576,
      name: '创业板',
      exchange: 'SH',
    },
    {
      code: '000977',
      price: 66.07,
      name: '浪潮信息',
      exchange: 'SZ',
    },
    {
      code: '603168',
      price: 15.8,
      name: '莎普爱思',
      exchange: 'SH',
    },
    {
      code: '300735',
      price: 34.99,
      name: '光弘科技',
      exchange: 'SZ',
    },
    {
      code: '002099',
      price: 10.11,
      name: '海翔药业',
      exchange: 'SZ',
    },
    {
      code: '002038',
      price: 16.09,
      name: '双鹭药业',
      exchange: 'SZ',
    },
    {
      code: '300290',
      price: 7.15,
      name: '荣科科技',
      exchange: 'SZ',
    },
    {
      code: '600744',
      price: 11.11,
      name: '华银电力',
      exchange: 'SH',
    },
    {
      code: '603595',
      price: 85.95,
      name: '东尼电子',
      exchange: 'SH',
    },
    {
      code: '600895',
      price: 28.89,
      name: '张江高科',
      exchange: 'SH',
    },
    {
      code: '001338',
      price: 26.53,
      name: '永顺太',
      exchange: 'SZ',
    },
    {
      code: '601678',
      price: 13.92,
      name: '滨化股份',
      exchange: 'SH',
    },
    {
      code: '000988',
      price: 46.39,
      name: '华工科技',
      exchange: 'SZ',
    },
    {
      code: '000681',
      price: 24.74,
      name: '视觉中国',
      exchange: 'SZ',
    },
    {
      code: '300467',
      price: 21.63,
      name: '讯游科技',
      exchange: 'SZ',
    },
    {
      code: '002031',
      price: 5.04,
      name: '巨轮智能',
      exchange: 'SZ',
    },
    {
      code: '600520',
      price: 24.61,
      name: '文一科技',
      exchange: 'SH',
    },
    {
      code: '601949',
      price: 16.93,
      name: '中国出版',
      exchange: 'SH',
    },
    {
      code: '603496',
      price: 45.97,
      name: '恒为科技',
      exchange: 'SH',
    },
    {
      code: '301169',
      price: 79.15,
      name: '零点有数',
      exchange: 'SZ',
    },
    {
      code: '301038',
      price: 26.56,
      name: '深水规划',
      exchange: 'SZ',
    },
    {
      code: '002129',
      price: 49.69,
      name: 'tcl中环',
      exchange: 'SZ',
    },
    {
      code: '002771',
      price: 39.39,
      name: '真视通',
      exchange: 'SZ',
    },
    {
      code: 'BK0486',
      price: 10332,
      name: '文化传媒',
      exchange: 'SH',
    },
    {
      code: '603220',
      price: 50.63,
      name: '中贝通信',
      exchange: 'SH',
    },
    {
      code: '002682',
      price: 8.2,
      name: '龙州股份',
      exchange: 'SZ',
    },
    {
      code: '000631',
      price: 4.95,
      name: '顺发恒业',
      exchange: 'SZ',
    },
    {
      code: '600839',
      price: 7.26,
      name: '四川长虹',
      exchange: 'SH',
    },
    {
      code: '300809',
      price: 33.68,
      name: '华辰装备',
      exchange: 'SZ',
    },
    {
      code: '603768',
      price: 30.16,
      name: '常青股份',
      exchange: 'SH',
    },
    {
      code: '603178',
      price: 45.84,
      name: '圣龙股份',
      exchange: 'SH',
    },
    {
      code: '002410',
      price: 65.39,
      name: '广联达',
      exchange: 'SZ',
    },
    {
      code: '002459',
      price: 59.47,
      name: '晶澳科技',
      exchange: 'SZ',
    },
    {
      code: '002292',
      price: 13.31,
      name: '奥飞娱乐',
      exchange: 'SZ',
    },
    {
      code: '002261',
      price: 23.2,
      name: '拓维信息',
      exchange: 'SZ',
    },
    {
      code: '600338',
      price: 50.89,
      name: '西藏珠峰',
      exchange: 'SH',
    },
    {
      code: '600355',
      price: 7.57,
      name: '精伦电子',
      exchange: 'SH',
    },
    {
      code: '000536',
      price: 5.8,
      name: '华映科技',
      exchange: 'SZ',
    },
    {
      code: '603829',
      price: 22.5,
      name: '洛凯股份',
      exchange: 'SH',
    },
    {
      code: '603863',
      price: 40.7,
      name: '松炀资源',
      exchange: 'SH',
    },
    {
      code: '603906',
      price: 70.85,
      name: '龙蟠科技',
      exchange: 'SH',
    },
    {
      code: '002898',
      price: 20.02,
      name: '赛隆药业',
      exchange: 'SZ',
    },
    {
      code: '603101',
      price: 8.99,
      name: '汇嘉时代',
      exchange: 'SH',
    },
    {
      code: '603178',
      price: 45.84,
      name: '圣龙股份',
      exchange: 'SH',
    },
    {
      code: '300255',
      price: 17.98,
      name: '常山药业',
      exchange: 'SZ',
    },
    {
      code: '300123',
      price: 10.07,
      name: '亚光科技',
      exchange: 'SZ',
    },
    {
      code: '605117',
      price: 252.09,
      name: '德业股份',
      exchange: 'SH',
    },
    {
      code: '000965',
      price: 11.44,
      name: '天保基建',
      exchange: 'SZ',
    },
    {
      code: '000716',
      price: 11.25,
      name: '黑芝麻',
      exchange: 'SZ',
    },
    {
      code: '002877',
      price: 13.7,
      name: '智能自控',
      exchange: 'SZ',
    },
    {
      code: '600683',
      price: 9.11,
      name: '京投发展',
      exchange: 'SH',
    },
    {
      code: '000965',
      price: 11.44,
      name: '天保基建',
      exchange: 'SZ',
    },
    {
      code: '002605',
      price: 48.2,
      name: '姚记科技',
      exchange: 'SZ',
    },
    {
      code: '002981',
      price: 46.53,
      name: '朝阳科技',
      exchange: 'SZ',
    },
    {
      code: '002898',
      price: 20.02,
      name: '赛隆药业',
      exchange: 'SZ',
    },
    {
      code: '603089',
      price: 15.41,
      name: '正裕工业',
      exchange: 'SH',
    },
    {
      code: '600186',
      price: 8.24,
      name: '莲花健康',
      exchange: 'SH',
    },
    {
      code: '300210',
      price: 10.51,
      name: '森远股份',
      exchange: 'SZ',
    },
    {
      code: '002931',
      price: 22.66,
      name: '锋龙股份',
      exchange: 'SZ',
    },
    {
      code: '603390',
      price: 15.17,
      name: '通达电气',
      exchange: 'SH',
    },
    {
      code: '603158',
      price: 13.28,
      name: '腾龙股份',
      exchange: 'SH',
    },
    {
      code: '300364',
      price: 28.96,
      name: '中文在线',
      exchange: 'SZ',
    },
    {
      code: '601127',
      price: 99.97,
      name: '赛力斯',
      exchange: 'SH',
    },
    {
      code: '603266',
      price: 47.95,
      name: '天龙股份',
      exchange: 'SH',
    },
    {
      code: '300280',
      price: 58,
      name: '紫天科技',
      exchange: 'SZ',
    },
    {
      code: '002457',
      price: 12.79,
      name: '青龙管业',
      exchange: 'SZ',
    },
    {
      code: '002090',
      price: 21.75,
      name: '金智科技',
      exchange: 'SZ',
    },
    {
      code: '300491',
      price: 36.9,
      name: '通合科技',
      exchange: 'SZ',
    },
    {
      code: '600630',
      price: 11.46,
      name: '龙头股份',
      exchange: 'SH',
    },
    {
      code: '603123',
      price: 16.93,
      name: '翠微股份',
      exchange: 'SH',
    },
    {
      code: '002514',
      price: 18.43,
      name: '宝馨科技',
      exchange: 'SZ',
    },
    {
      code: '002682',
      price: 8.2,
      name: '龙洲股份',
      exchange: 'SZ',
    },
    {
      code: '000541',
      price: 9.14,
      name: '佛山照明',
      exchange: 'SZ',
    },
    {
      code: '688166',
      price: 46.88,
      name: '博瑞医药',
      exchange: 'SH',
    },
    {
      code: '300630',
      price: 32.5,
      name: '普利制药',
      exchange: 'SZ',
    },
    {
      code: '603219',
      price: 18.43,
      name: '富家股份',
      exchange: 'SH',
    },
    {
      code: '601900',
      price: 29.17,
      name: '南方传媒',
      exchange: 'SH',
    },
    {
      code: '300337',
      price: 11.99,
      name: '银邦股份',
      exchange: 'SZ',
    },
    {
      code: '300063',
      price: 9.1,
      name: '天龙集团',
      exchange: 'SZ',
    },
    {
      code: '300269',
      price: 5.66,
      name: '联建光电',
      exchange: 'SZ',
    },
    {
      code: '600222',
      price: 8.08,
      name: '太龙药业',
      exchange: 'SH',
    },
    {
      code: '600415',
      price: 10.82,
      name: '小商品城',
      exchange: 'SH',
    },
    {
      code: '600143',
      price: 31.77,
      name: '金发科技',
      exchange: 'SH',
    },
    {
      code: '600589',
      price: 6.22,
      name: '*ST榕泰',
      exchange: 'SH',
    },
    {
      code: '002528',
      price: 14.18,
      name: '英飞拓',
      exchange: 'SZ',
    },
    {
      code: '300880',
      price: 35.88,
      name: '迦南智能',
      exchange: 'SZ',
    },
    {
      code: '002771',
      price: 39.39,
      name: '真视通',
      exchange: 'SZ',
    },
    {
      code: '002988',
      price: 38.48,
      name: '豪美新材',
      exchange: 'SZ',
    },
    {
      name: '东莞控股',
      code: '000828',
      price: 14.36,
      exchange: 'SZ',
    },
    {
      name: '浙江新能',
      code: '600032',
      price: 19.59,
      exchange: 'SH',
    },
    {
      name: '科大讯飞',
      code: '002230',
      price: 81.9,
      exchange: 'SZ',
    },
    {
      name: '富乐德',
      code: '301297',
      price: 38.5,
      exchange: 'SZ',
    },
    {
      name: '开创电气',
      code: '301448',
      price: 54.19,
      exchange: 'SZ',
    },
    {
      name: '龙溪股份',
      code: '600592',
      price: 14.36,
      exchange: 'SH',
    },
    {
      name: '皇庭国际',
      code: '000056',
      price: 6.07,
      exchange: 'SZ',
    },
    {
      name: '德方纳米',
      code: '300769',
      price: 266.27,
      exchange: 'SZ',
    },
    {
      name: '君逸数码',
      code: '301172',
      price: 66.66,
      exchange: 'SZ',
    },
    {
      name: '北汽蓝谷',
      code: '600733',
      price: 8,
      exchange: 'SH',
    },
    {
      name: '江铃汽车',
      code: '000550',
      price: 23.97,
      exchange: 'SZ',
    },
    {
      name: '森远股份',
      code: '300210',
      price: 10.93,
      exchange: 'SZ',
    },
    {
      name: '三超新材',
      code: '300554',
      price: 39.5,
      exchange: 'SZ',
    },
    {
      name: '多伦科技',
      code: '603528',
      price: 14.5,
      exchange: 'SH',
    },
    {
      name: '汇纳科技',
      code: '300609',
      price: 40.77,
      exchange: 'SZ',
    },
    {
      name: '中马传动',
      code: '603767',
      price: 23.5,
      exchange: 'SH',
    },
    {
      name: '永太科技',
      code: '002326',
      price: 80.93,
      exchange: 'SZ',
    },
    {
      name: '亚翔集成',
      code: '603929',
      price: 32.94,
      exchange: 'SH',
    },
    {
      name: '龙高股份',
      code: '605086',
      price: 39.83,
      exchange: 'SH',
    },
    {
      name: '西陇科学',
      code: '002584',
      price: 14.3,
      exchange: 'SZ',
    },
    {
      name: '直真科技',
      code: '003007',
      price: 45.13,
      exchange: 'SZ',
    },
    {
      name: '延华智能',
      code: '002178',
      price: 7.22,
      exchange: 'SZ',
    },
    {
      name: '统一股份',
      code: '600506',
      price: 19.48,
      exchange: 'SH',
    },
    {
      name: '龙宇股份',
      code: '603003',
      price: 15.29,
      exchange: 'SH',
    },
    {
      name: '江淮汽车',
      code: '600418',
      price: 21.82,
      exchange: 'SH',
    },
    {
      name: '三柏硕',
      code: '001300',
      price: 31.13,
      exchange: 'SZ',
    },
    {
      name: '天银机电',
      code: '300342',
      price: 23.6,
      exchange: 'SZ',
    },
    {
      name: '恒润股份',
      code: '603985',
      price: 54.92,
      exchange: 'SH',
    },
    {
      name: '德龙汇能',
      code: '000593',
      price: 9.33,
      exchange: 'SZ',
    },
    {
      name: '传智教育',
      code: '003032',
      price: 20.96,
      exchange: 'SZ',
    },
    {
      name: '海天味业',
      code: '603288',
      price: 126.2,
      exchange: 'SH',
    },
    {
      name: '农发种业',
      code: '600313',
      price: 15.87,
      exchange: 'SH',
    },
    {
      name: '皖通科技',
      code: '002331',
      price: 13.45,
      exchange: 'SZ',
    },
    {
      name: '惠威科技',
      code: '002888',
      price: 25.55,
      exchange: 'SZ',
    },
    {
      name: '文一科技',
      code: '600520',
      price: 42.34,
      exchange: 'SH',
    },
    {
      name: '华力创通',
      code: '300045',
      price: 36.83,
      exchange: 'SZ',
    },
    {
      name: '力源信息',
      code: '300184',
      price: 7.9,
      exchange: 'SZ',
    },
    {
      name: '伟时电子',
      code: '605218',
      price: 34.84,
      exchange: 'SH',
    },
    {
      name: '碳酸锂期货',
      code: null,
      price: 240450,
      exchange: 'SH',
    },
    {
      name: '日盈电子',
      code: '603286',
      price: 41.51,
      exchange: 'SH',
    },
    {
      name: '大恒科技',
      code: '600288',
      price: 15.27,
      exchange: 'SH',
    },
    {
      name: 'st同达',
      code: '600647',
      price: 55.92,
      exchange: 'SH',
    },
    {
      name: '威帝股份',
      code: '603023',
      price: 8.2,
      exchange: 'SH',
    },
    {
      name: '日海智能',
      code: '002313',
      price: 12.69,
      exchange: 'SZ',
    },
    {
      name: '先锋电子',
      code: '002767',
      price: 20.83,
      exchange: 'SZ',
    },
    {
      name: '凯众股份',
      code: '603037',
      price: 28.92,
      exchange: 'SH',
    },
    {
      name: '金溢科技',
      code: '002869',
      price: 27.35,
      exchange: 'SZ',
    },
    {
      name: '中富电路',
      code: '300814',
      price: 46.39,
      exchange: 'SZ',
    },
    {
      name: '精研科技',
      code: '300709',
      price: 39.38,
      exchange: 'SZ',
    },
    {
      name: '上海沪工',
      code: '603131',
      price: 20.37,
      exchange: 'SH',
    },
    {
      name: '东安动力',
      code: '600178',
      price: 20.23,
      exchange: 'SH',
    },
    {
      name: '果麦文化',
      price: 71.81,
      code: '301052',
      exchange: 'SZ',
    },
    {
      name: '昂立教育',
      price: 15.09,
      code: '600661',
      exchange: 'SH',
    },
    {
      name: '云内动力',
      price: 3.91,
      code: '000903',
      exchange: 'SZ',
    },
    {
      name: '恩捷股份',
      price: 318.32,
      code: '002812',
      exchange: 'SZ',
    },
    {
      name: '省广集团',
      price: 7.88,
      code: '002400',
      exchange: 'SZ',
    },
    {
      name: '天赐材料',
      price: 84.41,
      code: '002709',
      exchange: 'SZ',
    },
    {
      name: '融捷股份',
      price: 192.92,
      code: '002192',
      exchange: 'SZ',
    },
    {
      name: '宁德时代',
      price: 382.68,
      code: '300750',
      exchange: 'SZ',
    },
    {
      code: '603799',
      price: 115.72,
      name: '华友钴业',
      exchange: 'SH',
    },
    {
      code: '002514',
      price: 12,
      name: '宝馨科技',
      exchange: 'SZ',
    },
    {
      code: '300576',
      price: 58.28,
      name: '容大感光',
      exchange: 'SZ',
    },
    {
      code: '300088',
      price: 8.09,
      name: '长信科技',
      exchange: 'SZ',
    },
    {
      code: '600560',
      price: 19.6,
      name: '金自天正',
      exchange: 'SH',
    },
    {
      code: '002962',
      price: 20.8,
      name: '五方光电',
      exchange: 'SZ',
    },
    {
      code: '300552',
      price: 41.78,
      name: '万集科技',
      exchange: 'SZ',
    },
    {
      code: '300857',
      price: 63.71,
      name: '协创数据',
      exchange: 'SZ',
    },
    {
      code: '603189',
      price: 22.41,
      name: '网达软件',
      exchange: 'SH',
    },
    {
      code: '600715',
      price: 4.2,
      name: '文投控股',
      exchange: 'SH',
    },
    {
      code: '600128',
      price: 12.95,
      name: '苏豪弘业',
      exchange: 'SH',
    },
    {
      code: '600678',
      price: 11.7,
      name: '四川金顶',
      exchange: 'SH',
    },
    {
      code: '002712',
      price: 8.5,
      name: '思美传媒',
      exchange: 'SZ',
    },
    {
      code: '301151',
      price: 31.73,
      name: '冠龙节能',
      exchange: 'SZ',
    },
    {
      code: '600571',
      price: 19.8,
      name: '信雅达',
      exchange: 'SH',
    },
    {
      code: '300199',
      price: 20.88,
      name: '翰宇药业',
      exchange: 'SZ',
    },
    {
      code: '603211',
      price: 25.78,
      name: '晋拓股份',
      exchange: 'SH',
    },
    {
      code: '300313',
      price: 15.78,
      name: 'st天山',
      exchange: 'SZ',
    },
    {
      code: '300136',
      price: 28.09,
      name: '信维通信',
      exchange: 'SZ',
    },
    {
      code: '603629',
      price: 40.92,
      name: '利通电子',
      exchange: 'SH',
    },
    {
      code: '301128',
      price: 66.66,
      name: '强瑞技术',
      exchange: 'SZ',
    },
    {
      code: '600794',
      price: 4.63,
      name: '保税科技',
      exchange: 'SH',
    },
    {
      code: '600250',
      price: 17.59,
      name: '南京商旅',
      exchange: 'SH',
    },
    {
      code: '600698',
      price: 7.39,
      name: '湖南天雁',
      exchange: 'SH',
    },
    {
      code: '603002',
      price: 8.99,
      name: '宏昌电子',
      exchange: 'SH',
    },
    {
      code: '603353',
      price: 38.31,
      name: '和顺石油',
      exchange: 'SH',
    },
    {
      code: '603991',
      price: 61.73,
      name: '至正股份',
      exchange: 'SH',
    },
    {
      code: '605577',
      price: 32.69,
      name: '龙版传媒',
      exchange: 'SH',
    },
    {
      code: '600053',
      price: 20.9,
      name: '九鼎投资',
      exchange: 'SH',
    },
    {
      code: '301111',
      price: 33.47,
      name: '粤万年青',
      exchange: 'SZ',
    },
    {
      code: '600513',
      price: 14.4,
      name: '联环药业',
      exchange: 'SH',
    },
    {
      code: '300928',
      price: 72.01,
      name: '华安鑫创',
      exchange: 'SZ',
    },
    {
      code: '603153',
      price: 29.98,
      name: '上海建科',
      exchange: 'SH',
    },
    {
      code: '603066',
      price: 14.61,
      name: '音飞存储',
      exchange: 'SH',
    },
    {
      code: '000421',
      price: 9.72,
      name: '南京公用',
      exchange: 'SZ',
    },
    {
      code: '600992',
      price: 38.77,
      name: '贵绳股份',
      exchange: 'SH',
    },
    {
      code: '603789',
      price: 15.95,
      name: '星光农机',
      exchange: 'SH',
    },
    {
      code: '603888',
      price: 42.71,
      name: '新华网',
      exchange: 'SH',
    },
    {
      code: '300624',
      price: 172.2,
      name: '万兴科技',
      exchange: 'SZ',
    },
    {
      code: '601138',
      price: 26.71,
      name: '工业富联',
      exchange: 'SH',
    },
    {
      code: '300475',
      price: 44,
      name: '香农芯创',
      exchange: 'SZ',
    },
    {
      code: '301255',
      price: 70,
      name: '通力科技',
      exchange: 'SZ',
    },
    {
      code: '000610',
      price: 23,
      name: '西安旅游',
      exchange: 'SZ',
    },
    {
      code: '002238',
      price: 17.86,
      name: '天威视讯',
      exchange: 'SZ',
    },
    {
      code: '600141',
      price: 56.88,
      name: '兴发集团',
      exchange: 'SH',
    },
    {
      code: '002539',
      price: 22.8,
      name: '云图控股',
      exchange: 'SZ',
    },
    {
      code: '600328',
      price: 23.11,
      name: '中盐化工',
      exchange: 'SH',
    },
    {
      code: '000422',
      price: 34.9,
      name: '湖北宜化',
      exchange: 'SZ',
    },
    {
      code: '002456',
      price: 12.3,
      name: '欧菲光',
      exchange: 'SZ',
    },
    {
      code: '603721',
      price: 42.89,
      name: '中广天泽',
      exchange: 'SH',
    },
    {
      code: '000572',
      price: 6.8,
      name: '海马汽车',
      exchange: 'SZ',
    },
    {
      code: '300949',
      price: 85.46,
      name: '奥雅股份',
      exchange: 'SZ',
    },
    {
      code: '300781',
      price: 61.7,
      name: '因赛集团',
      exchange: 'SZ',
    },
    {
      code: '603598',
      price: 29.16,
      name: '引力传媒',
      exchange: 'SH',
    },
    {
      code: '603660',
      price: 12.08,
      name: '苏州科达',
      exchange: 'SH',
    },
    {
      code: '600287',
      price: 9.02,
      name: '江苏瞬天',
      exchange: 'SH',
    },
    {
      code: '605118',
      price: 29.27,
      name: '力鼎光电',
      exchange: 'SH',
    },
    {
      code: '002660',
      price: 14.58,
      name: '茂硕电源',
      exchange: 'SZ',
    },
  ]);